/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.domainToDto.domainToDTO;

import com.stefanvuckovic.domainmodel.domainModel.Expression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Mapping Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.stefanvuckovic.domainToDto.domainToDTO.EntityMappingExpression#getMappedEntity <em>Mapped Entity</em>}</li>
 *   <li>{@link com.stefanvuckovic.domainToDto.domainToDTO.EntityMappingExpression#getMapper <em>Mapper</em>}</li>
 * </ul>
 *
 * @see com.stefanvuckovic.domainToDto.domainToDTO.DomainToDTOPackage#getEntityMappingExpression()
 * @model
 * @generated
 */
public interface EntityMappingExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Mapped Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapped Entity</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapped Entity</em>' containment reference.
   * @see #setMappedEntity(Expression)
   * @see com.stefanvuckovic.domainToDto.domainToDTO.DomainToDTOPackage#getEntityMappingExpression_MappedEntity()
   * @model containment="true"
   * @generated
   */
  Expression getMappedEntity();

  /**
   * Sets the value of the '{@link com.stefanvuckovic.domainToDto.domainToDTO.EntityMappingExpression#getMappedEntity <em>Mapped Entity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapped Entity</em>' containment reference.
   * @see #getMappedEntity()
   * @generated
   */
  void setMappedEntity(Expression value);

  /**
   * Returns the value of the '<em><b>Mapper</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapper</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapper</em>' reference.
   * @see #setMapper(Mapper)
   * @see com.stefanvuckovic.domainToDto.domainToDTO.DomainToDTOPackage#getEntityMappingExpression_Mapper()
   * @model
   * @generated
   */
  Mapper getMapper();

  /**
   * Sets the value of the '{@link com.stefanvuckovic.domainToDto.domainToDTO.EntityMappingExpression#getMapper <em>Mapper</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapper</em>' reference.
   * @see #getMapper()
   * @generated
   */
  void setMapper(Mapper value);

} // EntityMappingExpression
