/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.uidsl.uIDSL.impl;

import com.stefanvuckovic.domainmodel.domainModel.impl.AttributeTypeImpl;

import com.stefanvuckovic.uidsl.uIDSL.CollectionGeneralType;
import com.stefanvuckovic.uidsl.uIDSL.UIDSLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Collection General Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CollectionGeneralTypeImpl extends AttributeTypeImpl implements CollectionGeneralType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CollectionGeneralTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UIDSLPackage.Literals.COLLECTION_GENERAL_TYPE;
  }

} //CollectionGeneralTypeImpl
