/*
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.domainToDto.ui;

import com.google.inject.Injector;
import com.stefanvuckovic.domainToDto.ui.internal.DomainToDtoActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainToDTOExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DomainToDtoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DomainToDtoActivator.getInstance().getInjector(DomainToDtoActivator.COM_STEFANVUCKOVIC_DOMAINTODTO_DOMAINTODTO);
	}
	
}
