/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.uidsl.uIDSL;

import com.stefanvuckovic.domainmodel.domainModel.AttributeType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collection General Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.stefanvuckovic.uidsl.uIDSL.UIDSLPackage#getCollectionGeneralType()
 * @model
 * @generated
 */
public interface CollectionGeneralType extends AttributeType
{
} // CollectionGeneralType
