/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.uidsl.uIDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Allowed Components</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.stefanvuckovic.uidsl.uIDSL.CustomAllowedComponents#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see com.stefanvuckovic.uidsl.uIDSL.UIDSLPackage#getCustomAllowedComponents()
 * @model
 * @generated
 */
public interface CustomAllowedComponents extends AllowedNestedComponents
{
  /**
   * Returns the value of the '<em><b>Components</b></em>' reference list.
   * The list contents are of type {@link com.stefanvuckovic.uidsl.uIDSL.UIComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Components</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' reference list.
   * @see com.stefanvuckovic.uidsl.uIDSL.UIDSLPackage#getCustomAllowedComponents_Components()
   * @model
   * @generated
   */
  EList<UIComponent> getComponents();

} // CustomAllowedComponents
