/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.uidsl.uIDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Template</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.stefanvuckovic.uidsl.uIDSL.UIDSLPackage#getTemplate()
 * @model
 * @generated
 */
public interface Template extends UIContainer
{
} // Template
