/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.uidsl.uIDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.stefanvuckovic.uidsl.uIDSL.UIDSLPackage#getTypeExpression()
 * @model
 * @generated
 */
public interface TypeExpression extends EObject
{
} // TypeExpression
