/*
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.dto.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DTOAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/stefanvuckovic/dto/parser/antlr/internal/InternalDTO.tokens");
	}
}
