/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.dto;

import com.stefanvuckovic.dto.DTOStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DTOStandaloneSetup extends DTOStandaloneSetupGenerated {
  public static void doSetup() {
    DTOStandaloneSetup _dTOStandaloneSetup = new DTOStandaloneSetup();
    _dTOStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
