/*
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.domainmodel.ide.contentassist.antlr;

import com.google.inject.Inject;
import com.stefanvuckovic.domainmodel.ide.contentassist.antlr.internal.InternalDomainModelParser;
import com.stefanvuckovic.domainmodel.services.DomainModelGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class DomainModelParser extends AbstractContentAssistParser {

	@Inject
	private DomainModelGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDomainModelParser createParser() {
		InternalDomainModelParser result = new InternalDomainModelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getConceptAccess().getAlternatives(), "rule__Concept__Alternatives");
					put(grammarAccess.getConstantAccess().getAlternatives(), "rule__Constant__Alternatives");
					put(grammarAccess.getConstantAccess().getValueAlternatives_3_1_0(), "rule__Constant__ValueAlternatives_3_1_0");
					put(grammarAccess.getOptionAccess().getAlternatives(), "rule__Option__Alternatives");
					put(grammarAccess.getEntityOptionAccess().getAlternatives(), "rule__EntityOption__Alternatives");
					put(grammarAccess.getInheritanceMappingTypeAccess().getTypeAlternatives_0(), "rule__InheritanceMappingType__TypeAlternatives_0");
					put(grammarAccess.getAttributeTypeAccess().getAlternatives(), "rule__AttributeType__Alternatives");
					put(grammarAccess.getSingleTypeAccess().getAlternatives(), "rule__SingleType__Alternatives");
					put(grammarAccess.getBasicTypeAccess().getAlternatives(), "rule__BasicType__Alternatives");
					put(grammarAccess.getAttributeOptionAccess().getAlternatives(), "rule__AttributeOption__Alternatives");
					put(grammarAccess.getCardinalityTypeAccess().getAlternatives(), "rule__CardinalityType__Alternatives");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getEntityAccess().getGroup_2(), "rule__Entity__Group_2__0");
					put(grammarAccess.getEntityAccess().getGroup_3(), "rule__Entity__Group_3__0");
					put(grammarAccess.getEntityAccess().getGroup_3_3(), "rule__Entity__Group_3_3__0");
					put(grammarAccess.getEnumAccess().getGroup(), "rule__Enum__Group__0");
					put(grammarAccess.getEnumLiteralAccess().getGroup(), "rule__EnumLiteral__Group__0");
					put(grammarAccess.getEnumLiteralAccess().getGroup_1(), "rule__EnumLiteral__Group_1__0");
					put(grammarAccess.getEnumLiteralAccess().getGroup_1_2(), "rule__EnumLiteral__Group_1_2__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getConstantAccess().getGroup_0(), "rule__Constant__Group_0__0");
					put(grammarAccess.getConstantAccess().getGroup_1(), "rule__Constant__Group_1__0");
					put(grammarAccess.getConstantAccess().getGroup_2(), "rule__Constant__Group_2__0");
					put(grammarAccess.getConstantAccess().getGroup_3(), "rule__Constant__Group_3__0");
					put(grammarAccess.getConstantAccess().getGroup_4(), "rule__Constant__Group_4__0");
					put(grammarAccess.getConstantAccess().getGroup_5(), "rule__Constant__Group_5__0");
					put(grammarAccess.getConstantAccess().getGroup_6(), "rule__Constant__Group_6__0");
					put(grammarAccess.getEntityOptionAccess().getGroup_0(), "rule__EntityOption__Group_0__0");
					put(grammarAccess.getEntityOptionAccess().getGroup_1(), "rule__EntityOption__Group_1__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_2(), "rule__Attribute__Group_2__0");
					put(grammarAccess.getAttributeAccess().getGroup_2_1(), "rule__Attribute__Group_2_1__0");
					put(grammarAccess.getBasicTypeAccess().getGroup_0(), "rule__BasicType__Group_0__0");
					put(grammarAccess.getBasicTypeAccess().getGroup_1(), "rule__BasicType__Group_1__0");
					put(grammarAccess.getBasicTypeAccess().getGroup_2(), "rule__BasicType__Group_2__0");
					put(grammarAccess.getBasicTypeAccess().getGroup_3(), "rule__BasicType__Group_3__0");
					put(grammarAccess.getBasicTypeAccess().getGroup_4(), "rule__BasicType__Group_4__0");
					put(grammarAccess.getBasicTypeAccess().getGroup_5(), "rule__BasicType__Group_5__0");
					put(grammarAccess.getCollectionTypeAccess().getGroup(), "rule__CollectionType__Group__0");
					put(grammarAccess.getAttributeOptionAccess().getGroup_0(), "rule__AttributeOption__Group_0__0");
					put(grammarAccess.getAttributeOptionAccess().getGroup_1(), "rule__AttributeOption__Group_1__0");
					put(grammarAccess.getAttributeOptionAccess().getGroup_2(), "rule__AttributeOption__Group_2__0");
					put(grammarAccess.getAttributeOptionAccess().getGroup_3(), "rule__AttributeOption__Group_3__0");
					put(grammarAccess.getStaticFieldSelectionAccess().getGroup(), "rule__StaticFieldSelection__Group__0");
					put(grammarAccess.getDumbSelectionMemberAccess().getGroup(), "rule__DumbSelectionMember__Group__0");
					put(grammarAccess.getDecimalAccess().getGroup(), "rule__Decimal__Group__0");
					put(grammarAccess.getModelAccess().getConceptsAssignment(), "rule__Model__ConceptsAssignment");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getSuperTypeAssignment_2_1(), "rule__Entity__SuperTypeAssignment_2_1");
					put(grammarAccess.getEntityAccess().getOptionsAssignment_3_2(), "rule__Entity__OptionsAssignment_3_2");
					put(grammarAccess.getEntityAccess().getOptionsAssignment_3_3_1(), "rule__Entity__OptionsAssignment_3_3_1");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_5(), "rule__Entity__AttributesAssignment_5");
					put(grammarAccess.getEnumAccess().getNameAssignment_1(), "rule__Enum__NameAssignment_1");
					put(grammarAccess.getEnumAccess().getAttributesAssignment_3(), "rule__Enum__AttributesAssignment_3");
					put(grammarAccess.getEnumAccess().getLiteralsAssignment_4(), "rule__Enum__LiteralsAssignment_4");
					put(grammarAccess.getEnumLiteralAccess().getNameAssignment_0(), "rule__EnumLiteral__NameAssignment_0");
					put(grammarAccess.getEnumLiteralAccess().getParamsAssignment_1_1(), "rule__EnumLiteral__ParamsAssignment_1_1");
					put(grammarAccess.getEnumLiteralAccess().getParamsAssignment_1_2_1(), "rule__EnumLiteral__ParamsAssignment_1_2_1");
					put(grammarAccess.getConstantAccess().getValueAssignment_0_1(), "rule__Constant__ValueAssignment_0_1");
					put(grammarAccess.getConstantAccess().getValueAssignment_1_1(), "rule__Constant__ValueAssignment_1_1");
					put(grammarAccess.getConstantAccess().getValueAssignment_2_1(), "rule__Constant__ValueAssignment_2_1");
					put(grammarAccess.getConstantAccess().getValueAssignment_3_1(), "rule__Constant__ValueAssignment_3_1");
					put(grammarAccess.getConstantAccess().getDayAssignment_4_1(), "rule__Constant__DayAssignment_4_1");
					put(grammarAccess.getConstantAccess().getMonthAssignment_4_3(), "rule__Constant__MonthAssignment_4_3");
					put(grammarAccess.getConstantAccess().getYearAssignment_4_5(), "rule__Constant__YearAssignment_4_5");
					put(grammarAccess.getConstantAccess().getValueAssignment_5_1(), "rule__Constant__ValueAssignment_5_1");
					put(grammarAccess.getEntityOptionAccess().getDeleteByFlagAssignment_0_1(), "rule__EntityOption__DeleteByFlagAssignment_0_1");
					put(grammarAccess.getEntityOptionAccess().getInheritanceMappingAssignment_1_3(), "rule__EntityOption__InheritanceMappingAssignment_1_3");
					put(grammarAccess.getInheritanceMappingTypeAccess().getTypeAssignment(), "rule__InheritanceMappingType__TypeAssignment");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_0(), "rule__Attribute__TypeAssignment_0");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getOptionsAssignment_2_0(), "rule__Attribute__OptionsAssignment_2_0");
					put(grammarAccess.getAttributeAccess().getOptionsAssignment_2_1_1(), "rule__Attribute__OptionsAssignment_2_1_1");
					put(grammarAccess.getRefTypeAccess().getReferenceAssignment(), "rule__RefType__ReferenceAssignment");
					put(grammarAccess.getCollectionTypeAccess().getOfTypeAssignment_2(), "rule__CollectionType__OfTypeAssignment_2");
					put(grammarAccess.getAttributeOptionAccess().getRequiredAssignment_0_1(), "rule__AttributeOption__RequiredAssignment_0_1");
					put(grammarAccess.getAttributeOptionAccess().getPartOfAssignment_1_1(), "rule__AttributeOption__PartOfAssignment_1_1");
					put(grammarAccess.getAttributeOptionAccess().getRelationshipOwnerAssignment_2_3(), "rule__AttributeOption__RelationshipOwnerAssignment_2_3");
					put(grammarAccess.getAttributeOptionAccess().getCardAssignment_3_3(), "rule__AttributeOption__CardAssignment_3_3");
					put(grammarAccess.getStaticFieldSelectionAccess().getReceiverAssignment_0(), "rule__StaticFieldSelection__ReceiverAssignment_0");
					put(grammarAccess.getStaticFieldSelectionAccess().getMemberAssignment_2(), "rule__StaticFieldSelection__MemberAssignment_2");
					put(grammarAccess.getDumbSelectionMemberAccess().getTypeAssignment_1(), "rule__DumbSelectionMember__TypeAssignment_1");
					put(grammarAccess.getDumbSelectionMemberAccess().getNameAssignment_2(), "rule__DumbSelectionMember__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalDomainModelParser typedParser = (InternalDomainModelParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DomainModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DomainModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
