/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.dto.dTO.impl;

import com.stefanvuckovic.domainmodel.domainModel.impl.BasicTypeImpl;

import com.stefanvuckovic.dto.dTO.DTOPackage;
import com.stefanvuckovic.dto.dTO.ImageType;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Image Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ImageTypeImpl extends BasicTypeImpl implements ImageType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImageTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DTOPackage.Literals.IMAGE_TYPE;
  }

} //ImageTypeImpl
