/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.dto.dTO;

import com.stefanvuckovic.domainmodel.domainModel.Concept;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.stefanvuckovic.dto.dTO.DTOModel#getConcepts <em>Concepts</em>}</li>
 * </ul>
 *
 * @see com.stefanvuckovic.dto.dTO.DTOPackage#getDTOModel()
 * @model
 * @generated
 */
public interface DTOModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Concepts</b></em>' containment reference list.
   * The list contents are of type {@link com.stefanvuckovic.domainmodel.domainModel.Concept}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concepts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concepts</em>' containment reference list.
   * @see com.stefanvuckovic.dto.dTO.DTOPackage#getDTOModel_Concepts()
   * @model containment="true"
   * @generated
   */
  EList<Concept> getConcepts();

} // DTOModel
