/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.dto.dTO;

import com.stefanvuckovic.domainmodel.domainModel.DomainModelPackage;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.stefanvuckovic.dto.dTO.DTOFactory
 * @model kind="package"
 * @generated
 */
public interface DTOPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dTO";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.stefanvuckovic.com/dto/DTO";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dTO";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DTOPackage eINSTANCE = com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl.init();

  /**
   * The meta object id for the '{@link com.stefanvuckovic.dto.dTO.impl.DTOModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.dto.dTO.impl.DTOModelImpl
   * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getDTOModel()
   * @generated
   */
  int DTO_MODEL = 0;

  /**
   * The feature id for the '<em><b>Concepts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_MODEL__CONCEPTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.dto.dTO.impl.DTOClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.dto.dTO.impl.DTOClassImpl
   * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getDTOClass()
   * @generated
   */
  int DTO_CLASS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_CLASS__NAME = DomainModelPackage.CONCEPT__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_CLASS__ATTRIBUTES = DomainModelPackage.CONCEPT__ATTRIBUTES;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_CLASS__SUPER_TYPE = DomainModelPackage.CONCEPT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DTO_CLASS_FEATURE_COUNT = DomainModelPackage.CONCEPT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.dto.dTO.impl.TextTypeImpl <em>Text Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.dto.dTO.impl.TextTypeImpl
   * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getTextType()
   * @generated
   */
  int TEXT_TYPE = 2;

  /**
   * The number of structural features of the '<em>Text Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_TYPE_FEATURE_COUNT = DomainModelPackage.BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.dto.dTO.impl.EmailTypeImpl <em>Email Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.dto.dTO.impl.EmailTypeImpl
   * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getEmailType()
   * @generated
   */
  int EMAIL_TYPE = 3;

  /**
   * The number of structural features of the '<em>Email Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMAIL_TYPE_FEATURE_COUNT = DomainModelPackage.BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.dto.dTO.impl.PasswordTypeImpl <em>Password Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.dto.dTO.impl.PasswordTypeImpl
   * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getPasswordType()
   * @generated
   */
  int PASSWORD_TYPE = 4;

  /**
   * The number of structural features of the '<em>Password Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PASSWORD_TYPE_FEATURE_COUNT = DomainModelPackage.BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.dto.dTO.impl.FileTypeImpl <em>File Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.dto.dTO.impl.FileTypeImpl
   * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getFileType()
   * @generated
   */
  int FILE_TYPE = 5;

  /**
   * The number of structural features of the '<em>File Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_TYPE_FEATURE_COUNT = DomainModelPackage.BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.dto.dTO.impl.ImageTypeImpl <em>Image Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.dto.dTO.impl.ImageTypeImpl
   * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getImageType()
   * @generated
   */
  int IMAGE_TYPE = 6;

  /**
   * The number of structural features of the '<em>Image Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_TYPE_FEATURE_COUNT = DomainModelPackage.BASIC_TYPE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.dto.dTO.DTOModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.stefanvuckovic.dto.dTO.DTOModel
   * @generated
   */
  EClass getDTOModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.stefanvuckovic.dto.dTO.DTOModel#getConcepts <em>Concepts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Concepts</em>'.
   * @see com.stefanvuckovic.dto.dTO.DTOModel#getConcepts()
   * @see #getDTOModel()
   * @generated
   */
  EReference getDTOModel_Concepts();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.dto.dTO.DTOClass <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see com.stefanvuckovic.dto.dTO.DTOClass
   * @generated
   */
  EClass getDTOClass();

  /**
   * Returns the meta object for the reference '{@link com.stefanvuckovic.dto.dTO.DTOClass#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see com.stefanvuckovic.dto.dTO.DTOClass#getSuperType()
   * @see #getDTOClass()
   * @generated
   */
  EReference getDTOClass_SuperType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.dto.dTO.TextType <em>Text Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Type</em>'.
   * @see com.stefanvuckovic.dto.dTO.TextType
   * @generated
   */
  EClass getTextType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.dto.dTO.EmailType <em>Email Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Email Type</em>'.
   * @see com.stefanvuckovic.dto.dTO.EmailType
   * @generated
   */
  EClass getEmailType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.dto.dTO.PasswordType <em>Password Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Password Type</em>'.
   * @see com.stefanvuckovic.dto.dTO.PasswordType
   * @generated
   */
  EClass getPasswordType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.dto.dTO.FileType <em>File Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File Type</em>'.
   * @see com.stefanvuckovic.dto.dTO.FileType
   * @generated
   */
  EClass getFileType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.dto.dTO.ImageType <em>Image Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image Type</em>'.
   * @see com.stefanvuckovic.dto.dTO.ImageType
   * @generated
   */
  EClass getImageType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DTOFactory getDTOFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.stefanvuckovic.dto.dTO.impl.DTOModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.dto.dTO.impl.DTOModelImpl
     * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getDTOModel()
     * @generated
     */
    EClass DTO_MODEL = eINSTANCE.getDTOModel();

    /**
     * The meta object literal for the '<em><b>Concepts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DTO_MODEL__CONCEPTS = eINSTANCE.getDTOModel_Concepts();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.dto.dTO.impl.DTOClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.dto.dTO.impl.DTOClassImpl
     * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getDTOClass()
     * @generated
     */
    EClass DTO_CLASS = eINSTANCE.getDTOClass();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DTO_CLASS__SUPER_TYPE = eINSTANCE.getDTOClass_SuperType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.dto.dTO.impl.TextTypeImpl <em>Text Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.dto.dTO.impl.TextTypeImpl
     * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getTextType()
     * @generated
     */
    EClass TEXT_TYPE = eINSTANCE.getTextType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.dto.dTO.impl.EmailTypeImpl <em>Email Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.dto.dTO.impl.EmailTypeImpl
     * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getEmailType()
     * @generated
     */
    EClass EMAIL_TYPE = eINSTANCE.getEmailType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.dto.dTO.impl.PasswordTypeImpl <em>Password Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.dto.dTO.impl.PasswordTypeImpl
     * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getPasswordType()
     * @generated
     */
    EClass PASSWORD_TYPE = eINSTANCE.getPasswordType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.dto.dTO.impl.FileTypeImpl <em>File Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.dto.dTO.impl.FileTypeImpl
     * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getFileType()
     * @generated
     */
    EClass FILE_TYPE = eINSTANCE.getFileType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.dto.dTO.impl.ImageTypeImpl <em>Image Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.dto.dTO.impl.ImageTypeImpl
     * @see com.stefanvuckovic.dto.dTO.impl.DTOPackageImpl#getImageType()
     * @generated
     */
    EClass IMAGE_TYPE = eINSTANCE.getImageType();

  }

} //DTOPackage
