/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.dto.dTO;

import com.stefanvuckovic.domainmodel.domainModel.AttributeOption;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Representation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.stefanvuckovic.dto.dTO.DTOPackage#getObjectRepresentation()
 * @model
 * @generated
 */
public interface ObjectRepresentation extends AttributeOption
{
} // ObjectRepresentation
