/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.dto.dTO;

import com.stefanvuckovic.domainmodel.domainModel.BasicType;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Password Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.stefanvuckovic.dto.dTO.DTOPackage#getPasswordType()
 * @model
 * @generated
 */
public interface PasswordType extends BasicType
{
} // PasswordType
