/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.domainmodel.domainModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.stefanvuckovic.domainmodel.domainModel.DomainModelFactory
 * @model kind="package"
 * @generated
 */
public interface DomainModelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "domainModel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.stefanvuckovic.com/domainmodel/DomainModel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "domainModel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DomainModelPackage eINSTANCE = com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl.init();

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.ModelImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Concepts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONCEPTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.ConceptImpl <em>Concept</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.ConceptImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getConcept()
   * @generated
   */
  int CONCEPT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCEPT__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCEPT__ATTRIBUTES = 1;

  /**
   * The number of structural features of the '<em>Concept</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCEPT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.EntityImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = CONCEPT__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRIBUTES = CONCEPT__ATTRIBUTES;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUPER_TYPE = CONCEPT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__OPTIONS = CONCEPT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = CONCEPT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EnumImpl <em>Enum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.EnumImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEnum()
   * @generated
   */
  int ENUM = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__NAME = CONCEPT__NAME;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__ATTRIBUTES = CONCEPT__ATTRIBUTES;

  /**
   * The feature id for the '<em><b>Literals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM__LITERALS = CONCEPT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_FEATURE_COUNT = CONCEPT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EnumLiteralImpl <em>Enum Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.EnumLiteralImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEnumLiteral()
   * @generated
   */
  int ENUM_LITERAL = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_LITERAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_LITERAL__PARAMS = 1;

  /**
   * The number of structural features of the '<em>Enum Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_LITERAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.ExpressionImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 5;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.OptionImpl <em>Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.OptionImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getOption()
   * @generated
   */
  int OPTION = 6;

  /**
   * The number of structural features of the '<em>Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EntityOptionImpl <em>Entity Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.EntityOptionImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEntityOption()
   * @generated
   */
  int ENTITY_OPTION = 7;

  /**
   * The number of structural features of the '<em>Entity Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_OPTION_FEATURE_COUNT = OPTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingTypeImpl <em>Inheritance Mapping Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getInheritanceMappingType()
   * @generated
   */
  int INHERITANCE_MAPPING_TYPE = 8;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHERITANCE_MAPPING_TYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Inheritance Mapping Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHERITANCE_MAPPING_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.SelectionMemberImpl <em>Selection Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.SelectionMemberImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getSelectionMember()
   * @generated
   */
  int SELECTION_MEMBER = 17;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTION_MEMBER__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTION_MEMBER__NAME = 1;

  /**
   * The number of structural features of the '<em>Selection Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTION_MEMBER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.AttributeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 9;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = SELECTION_MEMBER__TYPE;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = SELECTION_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__OPTIONS = SELECTION_MEMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = SELECTION_MEMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.AttributeTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getAttributeType()
   * @generated
   */
  int ATTRIBUTE_TYPE = 10;

  /**
   * The number of structural features of the '<em>Attribute Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.SingleTypeImpl <em>Single Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.SingleTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getSingleType()
   * @generated
   */
  int SINGLE_TYPE = 11;

  /**
   * The number of structural features of the '<em>Single Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_TYPE_FEATURE_COUNT = ATTRIBUTE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.BasicTypeImpl <em>Basic Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.BasicTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getBasicType()
   * @generated
   */
  int BASIC_TYPE = 12;

  /**
   * The number of structural features of the '<em>Basic Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_TYPE_FEATURE_COUNT = SINGLE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.RefTypeImpl <em>Ref Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.RefTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getRefType()
   * @generated
   */
  int REF_TYPE = 13;

  /**
   * The feature id for the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_TYPE__REFERENCE = SINGLE_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ref Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REF_TYPE_FEATURE_COUNT = SINGLE_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.CollectionTypeImpl <em>Collection Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.CollectionTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getCollectionType()
   * @generated
   */
  int COLLECTION_TYPE = 14;

  /**
   * The feature id for the '<em><b>Of Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_TYPE__OF_TYPE = ATTRIBUTE_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Collection Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_TYPE_FEATURE_COUNT = ATTRIBUTE_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.AttributeOptionImpl <em>Attribute Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.AttributeOptionImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getAttributeOption()
   * @generated
   */
  int ATTRIBUTE_OPTION = 15;

  /**
   * The number of structural features of the '<em>Attribute Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_OPTION_FEATURE_COUNT = OPTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.StaticFieldSelectionImpl <em>Static Field Selection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.StaticFieldSelectionImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getStaticFieldSelection()
   * @generated
   */
  int STATIC_FIELD_SELECTION = 16;

  /**
   * The feature id for the '<em><b>Receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_FIELD_SELECTION__RECEIVER = 0;

  /**
   * The feature id for the '<em><b>Member</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_FIELD_SELECTION__MEMBER = 1;

  /**
   * The number of structural features of the '<em>Static Field Selection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_FIELD_SELECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.IntConstantImpl <em>Int Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.IntConstantImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getIntConstant()
   * @generated
   */
  int INT_CONSTANT = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.LongConstantImpl <em>Long Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.LongConstantImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getLongConstant()
   * @generated
   */
  int LONG_CONSTANT = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONG_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Long Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONG_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.StringConstantImpl <em>String Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.StringConstantImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getStringConstant()
   * @generated
   */
  int STRING_CONSTANT = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.BoolConstantImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getBoolConstant()
   * @generated
   */
  int BOOL_CONSTANT = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DateConstantImpl <em>Date Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DateConstantImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDateConstant()
   * @generated
   */
  int DATE_CONSTANT = 22;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_CONSTANT__DAY = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_CONSTANT__MONTH = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_CONSTANT__YEAR = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Date Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DecimalConstantImpl <em>Decimal Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DecimalConstantImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDecimalConstant()
   * @generated
   */
  int DECIMAL_CONSTANT = 23;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECIMAL_CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Decimal Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECIMAL_CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.NullImpl <em>Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.NullImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getNull()
   * @generated
   */
  int NULL = 24;

  /**
   * The number of structural features of the '<em>Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EntityDeleteOptionImpl <em>Entity Delete Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.EntityDeleteOptionImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEntityDeleteOption()
   * @generated
   */
  int ENTITY_DELETE_OPTION = 25;

  /**
   * The feature id for the '<em><b>Delete By Flag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_DELETE_OPTION__DELETE_BY_FLAG = ENTITY_OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entity Delete Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_DELETE_OPTION_FEATURE_COUNT = ENTITY_OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingOptionImpl <em>Inheritance Mapping Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingOptionImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getInheritanceMappingOption()
   * @generated
   */
  int INHERITANCE_MAPPING_OPTION = 26;

  /**
   * The feature id for the '<em><b>Inheritance Mapping</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHERITANCE_MAPPING_OPTION__INHERITANCE_MAPPING = ENTITY_OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Inheritance Mapping Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INHERITANCE_MAPPING_OPTION_FEATURE_COUNT = ENTITY_OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.StringTypeImpl <em>String Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.StringTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getStringType()
   * @generated
   */
  int STRING_TYPE = 27;

  /**
   * The number of structural features of the '<em>String Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.IntTypeImpl <em>Int Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.IntTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getIntType()
   * @generated
   */
  int INT_TYPE = 28;

  /**
   * The number of structural features of the '<em>Int Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.LongTypeImpl <em>Long Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.LongTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getLongType()
   * @generated
   */
  int LONG_TYPE = 29;

  /**
   * The number of structural features of the '<em>Long Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONG_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.BoolTypeImpl <em>Bool Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.BoolTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getBoolType()
   * @generated
   */
  int BOOL_TYPE = 30;

  /**
   * The number of structural features of the '<em>Bool Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DateTypeImpl <em>Date Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DateTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDateType()
   * @generated
   */
  int DATE_TYPE = 31;

  /**
   * The number of structural features of the '<em>Date Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DecimalTypeImpl <em>Decimal Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DecimalTypeImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDecimalType()
   * @generated
   */
  int DECIMAL_TYPE = 32;

  /**
   * The number of structural features of the '<em>Decimal Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECIMAL_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.RequiredImpl <em>Required</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.RequiredImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getRequired()
   * @generated
   */
  int REQUIRED = 33;

  /**
   * The feature id for the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED__REQUIRED = ATTRIBUTE_OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Required</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRED_FEATURE_COUNT = ATTRIBUTE_OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.PartOfImpl <em>Part Of</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.PartOfImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getPartOf()
   * @generated
   */
  int PART_OF = 34;

  /**
   * The feature id for the '<em><b>Part Of</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART_OF__PART_OF = ATTRIBUTE_OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Part Of</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART_OF_FEATURE_COUNT = ATTRIBUTE_OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.RelationshipOwnerImpl <em>Relationship Owner</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.RelationshipOwnerImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getRelationshipOwner()
   * @generated
   */
  int RELATIONSHIP_OWNER = 35;

  /**
   * The feature id for the '<em><b>Relationship Owner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_OWNER__RELATIONSHIP_OWNER = ATTRIBUTE_OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Relationship Owner</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_OWNER_FEATURE_COUNT = ATTRIBUTE_OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.CardinalityImpl <em>Cardinality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.CardinalityImpl
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getCardinality()
   * @generated
   */
  int CARDINALITY = 36;

  /**
   * The feature id for the '<em><b>Card</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARDINALITY__CARD = ATTRIBUTE_OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cardinality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARDINALITY_FEATURE_COUNT = ATTRIBUTE_OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.stefanvuckovic.domainmodel.domainModel.CardinalityType <em>Cardinality Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.stefanvuckovic.domainmodel.domainModel.CardinalityType
   * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getCardinalityType()
   * @generated
   */
  int CARDINALITY_TYPE = 37;


  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.stefanvuckovic.domainmodel.domainModel.Model#getConcepts <em>Concepts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Concepts</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Model#getConcepts()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Concepts();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Concept <em>Concept</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concept</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Concept
   * @generated
   */
  EClass getConcept();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.Concept#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Concept#getName()
   * @see #getConcept()
   * @generated
   */
  EAttribute getConcept_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.stefanvuckovic.domainmodel.domainModel.Concept#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Concept#getAttributes()
   * @see #getConcept()
   * @generated
   */
  EReference getConcept_Attributes();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the reference '{@link com.stefanvuckovic.domainmodel.domainModel.Entity#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Entity#getSuperType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link com.stefanvuckovic.domainmodel.domainModel.Entity#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Entity#getOptions()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Options();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Enum <em>Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Enum
   * @generated
   */
  EClass getEnum();

  /**
   * Returns the meta object for the containment reference list '{@link com.stefanvuckovic.domainmodel.domainModel.Enum#getLiterals <em>Literals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Literals</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Enum#getLiterals()
   * @see #getEnum()
   * @generated
   */
  EReference getEnum_Literals();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.EnumLiteral <em>Enum Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Literal</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.EnumLiteral
   * @generated
   */
  EClass getEnumLiteral();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.EnumLiteral#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.EnumLiteral#getName()
   * @see #getEnumLiteral()
   * @generated
   */
  EAttribute getEnumLiteral_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.stefanvuckovic.domainmodel.domainModel.EnumLiteral#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.EnumLiteral#getParams()
   * @see #getEnumLiteral()
   * @generated
   */
  EReference getEnumLiteral_Params();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Option
   * @generated
   */
  EClass getOption();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.EntityOption <em>Entity Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity Option</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.EntityOption
   * @generated
   */
  EClass getEntityOption();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingType <em>Inheritance Mapping Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inheritance Mapping Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingType
   * @generated
   */
  EClass getInheritanceMappingType();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingType#getType()
   * @see #getInheritanceMappingType()
   * @generated
   */
  EAttribute getInheritanceMappingType_Type();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the containment reference list '{@link com.stefanvuckovic.domainmodel.domainModel.Attribute#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Attribute#getOptions()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Options();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.AttributeType <em>Attribute Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.AttributeType
   * @generated
   */
  EClass getAttributeType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.SingleType <em>Single Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.SingleType
   * @generated
   */
  EClass getSingleType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.BasicType <em>Basic Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Basic Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.BasicType
   * @generated
   */
  EClass getBasicType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.RefType <em>Ref Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ref Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.RefType
   * @generated
   */
  EClass getRefType();

  /**
   * Returns the meta object for the reference '{@link com.stefanvuckovic.domainmodel.domainModel.RefType#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reference</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.RefType#getReference()
   * @see #getRefType()
   * @generated
   */
  EReference getRefType_Reference();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.CollectionType <em>Collection Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.CollectionType
   * @generated
   */
  EClass getCollectionType();

  /**
   * Returns the meta object for the containment reference '{@link com.stefanvuckovic.domainmodel.domainModel.CollectionType#getOfType <em>Of Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Of Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.CollectionType#getOfType()
   * @see #getCollectionType()
   * @generated
   */
  EReference getCollectionType_OfType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.AttributeOption <em>Attribute Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Option</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.AttributeOption
   * @generated
   */
  EClass getAttributeOption();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.StaticFieldSelection <em>Static Field Selection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Static Field Selection</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.StaticFieldSelection
   * @generated
   */
  EClass getStaticFieldSelection();

  /**
   * Returns the meta object for the reference '{@link com.stefanvuckovic.domainmodel.domainModel.StaticFieldSelection#getReceiver <em>Receiver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Receiver</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.StaticFieldSelection#getReceiver()
   * @see #getStaticFieldSelection()
   * @generated
   */
  EReference getStaticFieldSelection_Receiver();

  /**
   * Returns the meta object for the reference '{@link com.stefanvuckovic.domainmodel.domainModel.StaticFieldSelection#getMember <em>Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Member</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.StaticFieldSelection#getMember()
   * @see #getStaticFieldSelection()
   * @generated
   */
  EReference getStaticFieldSelection_Member();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.SelectionMember <em>Selection Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selection Member</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.SelectionMember
   * @generated
   */
  EClass getSelectionMember();

  /**
   * Returns the meta object for the containment reference '{@link com.stefanvuckovic.domainmodel.domainModel.SelectionMember#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.SelectionMember#getType()
   * @see #getSelectionMember()
   * @generated
   */
  EReference getSelectionMember_Type();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.SelectionMember#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.SelectionMember#getName()
   * @see #getSelectionMember()
   * @generated
   */
  EAttribute getSelectionMember_Name();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.IntConstant <em>Int Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Constant</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.IntConstant
   * @generated
   */
  EClass getIntConstant();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.IntConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.IntConstant#getValue()
   * @see #getIntConstant()
   * @generated
   */
  EAttribute getIntConstant_Value();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.LongConstant <em>Long Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Long Constant</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.LongConstant
   * @generated
   */
  EClass getLongConstant();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.LongConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.LongConstant#getValue()
   * @see #getLongConstant()
   * @generated
   */
  EAttribute getLongConstant_Value();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.StringConstant <em>String Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Constant</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.StringConstant
   * @generated
   */
  EClass getStringConstant();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.StringConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.StringConstant#getValue()
   * @see #getStringConstant()
   * @generated
   */
  EAttribute getStringConstant_Value();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.BoolConstant <em>Bool Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Constant</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.BoolConstant
   * @generated
   */
  EClass getBoolConstant();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.BoolConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.BoolConstant#getValue()
   * @see #getBoolConstant()
   * @generated
   */
  EAttribute getBoolConstant_Value();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.DateConstant <em>Date Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date Constant</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DateConstant
   * @generated
   */
  EClass getDateConstant();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.DateConstant#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DateConstant#getDay()
   * @see #getDateConstant()
   * @generated
   */
  EAttribute getDateConstant_Day();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.DateConstant#getMonth <em>Month</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Month</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DateConstant#getMonth()
   * @see #getDateConstant()
   * @generated
   */
  EAttribute getDateConstant_Month();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.DateConstant#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DateConstant#getYear()
   * @see #getDateConstant()
   * @generated
   */
  EAttribute getDateConstant_Year();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.DecimalConstant <em>Decimal Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decimal Constant</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DecimalConstant
   * @generated
   */
  EClass getDecimalConstant();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.DecimalConstant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DecimalConstant#getValue()
   * @see #getDecimalConstant()
   * @generated
   */
  EAttribute getDecimalConstant_Value();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Null <em>Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Null</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Null
   * @generated
   */
  EClass getNull();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.EntityDeleteOption <em>Entity Delete Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity Delete Option</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.EntityDeleteOption
   * @generated
   */
  EClass getEntityDeleteOption();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.EntityDeleteOption#isDeleteByFlag <em>Delete By Flag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Delete By Flag</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.EntityDeleteOption#isDeleteByFlag()
   * @see #getEntityDeleteOption()
   * @generated
   */
  EAttribute getEntityDeleteOption_DeleteByFlag();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingOption <em>Inheritance Mapping Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inheritance Mapping Option</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingOption
   * @generated
   */
  EClass getInheritanceMappingOption();

  /**
   * Returns the meta object for the containment reference '{@link com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingOption#getInheritanceMapping <em>Inheritance Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inheritance Mapping</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.InheritanceMappingOption#getInheritanceMapping()
   * @see #getInheritanceMappingOption()
   * @generated
   */
  EReference getInheritanceMappingOption_InheritanceMapping();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.StringType <em>String Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.StringType
   * @generated
   */
  EClass getStringType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.IntType <em>Int Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.IntType
   * @generated
   */
  EClass getIntType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.LongType <em>Long Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Long Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.LongType
   * @generated
   */
  EClass getLongType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.BoolType <em>Bool Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.BoolType
   * @generated
   */
  EClass getBoolType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.DateType <em>Date Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DateType
   * @generated
   */
  EClass getDateType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.DecimalType <em>Decimal Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decimal Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.DecimalType
   * @generated
   */
  EClass getDecimalType();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Required <em>Required</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Required</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Required
   * @generated
   */
  EClass getRequired();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.Required#isRequired <em>Required</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Required</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Required#isRequired()
   * @see #getRequired()
   * @generated
   */
  EAttribute getRequired_Required();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.PartOf <em>Part Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Part Of</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.PartOf
   * @generated
   */
  EClass getPartOf();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.PartOf#isPartOf <em>Part Of</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Part Of</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.PartOf#isPartOf()
   * @see #getPartOf()
   * @generated
   */
  EAttribute getPartOf_PartOf();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.RelationshipOwner <em>Relationship Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship Owner</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.RelationshipOwner
   * @generated
   */
  EClass getRelationshipOwner();

  /**
   * Returns the meta object for the containment reference '{@link com.stefanvuckovic.domainmodel.domainModel.RelationshipOwner#getRelationshipOwner <em>Relationship Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relationship Owner</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.RelationshipOwner#getRelationshipOwner()
   * @see #getRelationshipOwner()
   * @generated
   */
  EReference getRelationshipOwner_RelationshipOwner();

  /**
   * Returns the meta object for class '{@link com.stefanvuckovic.domainmodel.domainModel.Cardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cardinality</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Cardinality
   * @generated
   */
  EClass getCardinality();

  /**
   * Returns the meta object for the attribute '{@link com.stefanvuckovic.domainmodel.domainModel.Cardinality#getCard <em>Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Card</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.Cardinality#getCard()
   * @see #getCardinality()
   * @generated
   */
  EAttribute getCardinality_Card();

  /**
   * Returns the meta object for enum '{@link com.stefanvuckovic.domainmodel.domainModel.CardinalityType <em>Cardinality Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Cardinality Type</em>'.
   * @see com.stefanvuckovic.domainmodel.domainModel.CardinalityType
   * @generated
   */
  EEnum getCardinalityType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DomainModelFactory getDomainModelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.ModelImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Concepts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONCEPTS = eINSTANCE.getModel_Concepts();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.ConceptImpl <em>Concept</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.ConceptImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getConcept()
     * @generated
     */
    EClass CONCEPT = eINSTANCE.getConcept();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCEPT__NAME = eINSTANCE.getConcept_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCEPT__ATTRIBUTES = eINSTANCE.getConcept_Attributes();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.EntityImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUPER_TYPE = eINSTANCE.getEntity_SuperType();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__OPTIONS = eINSTANCE.getEntity_Options();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EnumImpl <em>Enum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.EnumImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEnum()
     * @generated
     */
    EClass ENUM = eINSTANCE.getEnum();

    /**
     * The meta object literal for the '<em><b>Literals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM__LITERALS = eINSTANCE.getEnum_Literals();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EnumLiteralImpl <em>Enum Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.EnumLiteralImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEnumLiteral()
     * @generated
     */
    EClass ENUM_LITERAL = eINSTANCE.getEnumLiteral();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_LITERAL__NAME = eINSTANCE.getEnumLiteral_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_LITERAL__PARAMS = eINSTANCE.getEnumLiteral_Params();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.ExpressionImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.OptionImpl <em>Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.OptionImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getOption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getOption();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EntityOptionImpl <em>Entity Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.EntityOptionImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEntityOption()
     * @generated
     */
    EClass ENTITY_OPTION = eINSTANCE.getEntityOption();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingTypeImpl <em>Inheritance Mapping Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getInheritanceMappingType()
     * @generated
     */
    EClass INHERITANCE_MAPPING_TYPE = eINSTANCE.getInheritanceMappingType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INHERITANCE_MAPPING_TYPE__TYPE = eINSTANCE.getInheritanceMappingType_Type();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.AttributeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__OPTIONS = eINSTANCE.getAttribute_Options();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.AttributeTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getAttributeType()
     * @generated
     */
    EClass ATTRIBUTE_TYPE = eINSTANCE.getAttributeType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.SingleTypeImpl <em>Single Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.SingleTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getSingleType()
     * @generated
     */
    EClass SINGLE_TYPE = eINSTANCE.getSingleType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.BasicTypeImpl <em>Basic Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.BasicTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getBasicType()
     * @generated
     */
    EClass BASIC_TYPE = eINSTANCE.getBasicType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.RefTypeImpl <em>Ref Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.RefTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getRefType()
     * @generated
     */
    EClass REF_TYPE = eINSTANCE.getRefType();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REF_TYPE__REFERENCE = eINSTANCE.getRefType_Reference();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.CollectionTypeImpl <em>Collection Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.CollectionTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getCollectionType()
     * @generated
     */
    EClass COLLECTION_TYPE = eINSTANCE.getCollectionType();

    /**
     * The meta object literal for the '<em><b>Of Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION_TYPE__OF_TYPE = eINSTANCE.getCollectionType_OfType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.AttributeOptionImpl <em>Attribute Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.AttributeOptionImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getAttributeOption()
     * @generated
     */
    EClass ATTRIBUTE_OPTION = eINSTANCE.getAttributeOption();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.StaticFieldSelectionImpl <em>Static Field Selection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.StaticFieldSelectionImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getStaticFieldSelection()
     * @generated
     */
    EClass STATIC_FIELD_SELECTION = eINSTANCE.getStaticFieldSelection();

    /**
     * The meta object literal for the '<em><b>Receiver</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATIC_FIELD_SELECTION__RECEIVER = eINSTANCE.getStaticFieldSelection_Receiver();

    /**
     * The meta object literal for the '<em><b>Member</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATIC_FIELD_SELECTION__MEMBER = eINSTANCE.getStaticFieldSelection_Member();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.SelectionMemberImpl <em>Selection Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.SelectionMemberImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getSelectionMember()
     * @generated
     */
    EClass SELECTION_MEMBER = eINSTANCE.getSelectionMember();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTION_MEMBER__TYPE = eINSTANCE.getSelectionMember_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTION_MEMBER__NAME = eINSTANCE.getSelectionMember_Name();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.IntConstantImpl <em>Int Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.IntConstantImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getIntConstant()
     * @generated
     */
    EClass INT_CONSTANT = eINSTANCE.getIntConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_CONSTANT__VALUE = eINSTANCE.getIntConstant_Value();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.LongConstantImpl <em>Long Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.LongConstantImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getLongConstant()
     * @generated
     */
    EClass LONG_CONSTANT = eINSTANCE.getLongConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LONG_CONSTANT__VALUE = eINSTANCE.getLongConstant_Value();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.StringConstantImpl <em>String Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.StringConstantImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getStringConstant()
     * @generated
     */
    EClass STRING_CONSTANT = eINSTANCE.getStringConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_CONSTANT__VALUE = eINSTANCE.getStringConstant_Value();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.BoolConstantImpl <em>Bool Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.BoolConstantImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getBoolConstant()
     * @generated
     */
    EClass BOOL_CONSTANT = eINSTANCE.getBoolConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_CONSTANT__VALUE = eINSTANCE.getBoolConstant_Value();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DateConstantImpl <em>Date Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DateConstantImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDateConstant()
     * @generated
     */
    EClass DATE_CONSTANT = eINSTANCE.getDateConstant();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE_CONSTANT__DAY = eINSTANCE.getDateConstant_Day();

    /**
     * The meta object literal for the '<em><b>Month</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE_CONSTANT__MONTH = eINSTANCE.getDateConstant_Month();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE_CONSTANT__YEAR = eINSTANCE.getDateConstant_Year();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DecimalConstantImpl <em>Decimal Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DecimalConstantImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDecimalConstant()
     * @generated
     */
    EClass DECIMAL_CONSTANT = eINSTANCE.getDecimalConstant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECIMAL_CONSTANT__VALUE = eINSTANCE.getDecimalConstant_Value();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.NullImpl <em>Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.NullImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getNull()
     * @generated
     */
    EClass NULL = eINSTANCE.getNull();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.EntityDeleteOptionImpl <em>Entity Delete Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.EntityDeleteOptionImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getEntityDeleteOption()
     * @generated
     */
    EClass ENTITY_DELETE_OPTION = eINSTANCE.getEntityDeleteOption();

    /**
     * The meta object literal for the '<em><b>Delete By Flag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_DELETE_OPTION__DELETE_BY_FLAG = eINSTANCE.getEntityDeleteOption_DeleteByFlag();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingOptionImpl <em>Inheritance Mapping Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.InheritanceMappingOptionImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getInheritanceMappingOption()
     * @generated
     */
    EClass INHERITANCE_MAPPING_OPTION = eINSTANCE.getInheritanceMappingOption();

    /**
     * The meta object literal for the '<em><b>Inheritance Mapping</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INHERITANCE_MAPPING_OPTION__INHERITANCE_MAPPING = eINSTANCE.getInheritanceMappingOption_InheritanceMapping();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.StringTypeImpl <em>String Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.StringTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getStringType()
     * @generated
     */
    EClass STRING_TYPE = eINSTANCE.getStringType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.IntTypeImpl <em>Int Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.IntTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getIntType()
     * @generated
     */
    EClass INT_TYPE = eINSTANCE.getIntType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.LongTypeImpl <em>Long Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.LongTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getLongType()
     * @generated
     */
    EClass LONG_TYPE = eINSTANCE.getLongType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.BoolTypeImpl <em>Bool Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.BoolTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getBoolType()
     * @generated
     */
    EClass BOOL_TYPE = eINSTANCE.getBoolType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DateTypeImpl <em>Date Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DateTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDateType()
     * @generated
     */
    EClass DATE_TYPE = eINSTANCE.getDateType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.DecimalTypeImpl <em>Decimal Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DecimalTypeImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getDecimalType()
     * @generated
     */
    EClass DECIMAL_TYPE = eINSTANCE.getDecimalType();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.RequiredImpl <em>Required</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.RequiredImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getRequired()
     * @generated
     */
    EClass REQUIRED = eINSTANCE.getRequired();

    /**
     * The meta object literal for the '<em><b>Required</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REQUIRED__REQUIRED = eINSTANCE.getRequired_Required();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.PartOfImpl <em>Part Of</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.PartOfImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getPartOf()
     * @generated
     */
    EClass PART_OF = eINSTANCE.getPartOf();

    /**
     * The meta object literal for the '<em><b>Part Of</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PART_OF__PART_OF = eINSTANCE.getPartOf_PartOf();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.RelationshipOwnerImpl <em>Relationship Owner</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.RelationshipOwnerImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getRelationshipOwner()
     * @generated
     */
    EClass RELATIONSHIP_OWNER = eINSTANCE.getRelationshipOwner();

    /**
     * The meta object literal for the '<em><b>Relationship Owner</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP_OWNER__RELATIONSHIP_OWNER = eINSTANCE.getRelationshipOwner_RelationshipOwner();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.impl.CardinalityImpl <em>Cardinality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.CardinalityImpl
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getCardinality()
     * @generated
     */
    EClass CARDINALITY = eINSTANCE.getCardinality();

    /**
     * The meta object literal for the '<em><b>Card</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARDINALITY__CARD = eINSTANCE.getCardinality_Card();

    /**
     * The meta object literal for the '{@link com.stefanvuckovic.domainmodel.domainModel.CardinalityType <em>Cardinality Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.stefanvuckovic.domainmodel.domainModel.CardinalityType
     * @see com.stefanvuckovic.domainmodel.domainModel.impl.DomainModelPackageImpl#getCardinalityType()
     * @generated
     */
    EEnum CARDINALITY_TYPE = eINSTANCE.getCardinalityType();

  }

} //DomainModelPackage
