/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.domainmodel.domainModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.stefanvuckovic.domainmodel.domainModel.DomainModelPackage#getOption()
 * @model
 * @generated
 */
public interface Option extends EObject
{
} // Option
