/**
 * generated by Xtext 2.10.0
 */
package com.stefanvuckovic.domainmodel.domainModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship Owner</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.stefanvuckovic.domainmodel.domainModel.RelationshipOwner#getRelationshipOwner <em>Relationship Owner</em>}</li>
 * </ul>
 *
 * @see com.stefanvuckovic.domainmodel.domainModel.DomainModelPackage#getRelationshipOwner()
 * @model
 * @generated
 */
public interface RelationshipOwner extends AttributeOption
{
  /**
   * Returns the value of the '<em><b>Relationship Owner</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relationship Owner</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationship Owner</em>' containment reference.
   * @see #setRelationshipOwner(StaticFieldSelection)
   * @see com.stefanvuckovic.domainmodel.domainModel.DomainModelPackage#getRelationshipOwner_RelationshipOwner()
   * @model containment="true"
   * @generated
   */
  StaticFieldSelection getRelationshipOwner();

  /**
   * Sets the value of the '{@link com.stefanvuckovic.domainmodel.domainModel.RelationshipOwner#getRelationshipOwner <em>Relationship Owner</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relationship Owner</em>' containment reference.
   * @see #getRelationshipOwner()
   * @generated
   */
  void setRelationshipOwner(StaticFieldSelection value);

} // RelationshipOwner
